### ISSUE TITLE
[已解决] IP 为 127.0.0.1 时报错

### ISSUE THREAD

**Issue by ay-tony** [Mooling0602/IPLocation-MCDR#3]
使用本机 IP 登录，配置为百度 API 时无法正确显示 IP，控制台报错 
```
Exception in thread IPLoc-Query:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aytony/.local/share/virtualenv/mcdreforged/lib/python3.12/site-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/home/aytony/.local/share/virtualenv/mcdreforged/lib/python3.12/site-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/IPLocation-v0.1.4.mcdr/iploc/entry.py", line 27, in on_player_ip_logged
  File "plugins/IPLocation-v0.1.4.mcdr/iploc/api/baidu.py", line 21, in getIPLoc
IndexError: list index out of range
```

这时百度 API 返回的 `json` 文件是 
```json
{
    "status": "0",
    "t": "",
    "set_cache_time": "",
    "data": []
}
```

看了下源码，应当是 `api/baidu.py` 里面的处理逻辑可以修改一下。

**Comment by Mooling0602** [comment]
已注意到此问题，稍后将发布更新修复。

**Comment by Mooling0602** [comment]
由于开发用设备不便进行测试，请你从Pre-release下载v0.1.5帮助测试并确认问题是否解决
https://github.com/Mooling0602/IPLocation-MCDR/releases/tag/0.1.5

**Comment by Mooling0602** [comment]
确认问题已解决后请回复我，我将会同步此更新到MCDReforged插件仓库内

**Comment by Mooling0602** [comment]
你好，问题已解决，将发布v0.1.6版本修复此问题。

**Comment by ay-tony** [comment]
感谢，可以正常使用了！
